#pragma once


typedef enum {
	EN = 0,
	ZH,
	LANGUAGE_NUMTYPES
} LanguageType;

void SetLanguageType(LanguageType language);
LanguageType GetLanguageType();
void SetLanguageTypeFromTag(const char* langTagZ);

typedef enum {
	STRID_NONE,
	STRID_NAME,
	STRID_DESCRIPTION,

	STRID_SPLAT_ENABLE,
	STRID_SELECT_FOOTAGE_LAYER,

	STRID_ALIGN_TOPIC,
	STRID_ALIGN_ANCHOR_POSITION,
	STRID_ALIGN_SCALE,
	STRID_ALIGN_ROTATION_X,
	STRID_ALIGN_ROTATION_Y,
	STRID_ALIGN_ROTATION_Z,

	STRID_TRANSFORM_TOPIC,
	STRID_TRANSFORM_POSITION,
	STRID_TRANSFORM_SCALE,
	STRID_TRANSFORM_ROTATION_X,
	STRID_TRANSFORM_ROTATION_Y,
	STRID_TRANSFORM_ROTATION_Z,

	STRID_EFFECT_TOPIC,

	STRID_RENDER_TOPIC,
	STRID_RENDER_COLOR_ENABLE,
	STRID_RENDER_COLOR_GRADIENT,
	STRID_RENDER_COLOR_RAMP,
	STRID_RENDER_SHDEGREE,
	STRID_RENDER_COLOR_SHAPE_SIZE,
	STRID_RENDER_COLOR_SHAPE_SCALE_X,
	STRID_RENDER_COLOR_SHAPE_SCALE_Y,
	STRID_RENDER_COLOR_SHAPE_SCALE_Z,
	STRID_RENDER_COLOR_SHAPE_CENTER,
	STRID_RENDER_COLOR_SHAPE_FEATHER,

	STRID_CROP_TOPIC,
	STRID_CROP_ENABLE,
	STRID_CROP_INVERT,
	STRID_CROP_SHAPE_SIZE,
	STRID_CROP_SHAPE_SCALE_X,
	STRID_CROP_SHAPE_SCALE_Y,
	STRID_CROP_SHAPE_SCALE_Z,
	STRID_CROP_SHAPE_CENTER,
	STRID_CROP_SHAPE_FEATHER,

	STRID_SPLAT_SCALE_TOPIC,
	STRID_SPLAT_SCALE_ENABLE,
	STRID_SPLAT_SCALE_SIZE,
	STRID_SPLAT_SCALE_RAMP,
	STRID_SPLAT_SCALE_SHAPE_SIZE,
	STRID_SPLAT_SCALE_SHAPE_SCALE_X,
	STRID_SPLAT_SCALE_SHAPE_SCALE_Y,
	STRID_SPLAT_SCALE_SHAPE_SCALE_Z,
	STRID_SPLAT_SCALE_SHAPE_CENTER,
	STRID_SPLAT_SCALE_SHAPE_FEATHER,

	STRID_SPLAT_NOISE_TOPIC,
	STRID_SPLAT_NOISE_ENABLE,
	STRID_SPLAT_NOISE_SHAPE_SIZE,
	STRID_SPLAT_NOISE_SHAPE_SCALE_X,
	STRID_SPLAT_NOISE_SHAPE_SCALE_Y,
	STRID_SPLAT_NOISE_SHAPE_SCALE_Z,
	STRID_SPLAT_NOISE_SHAPE_CENTER,
	STRID_SPLAT_NOISE_SHAPE_FEATHER,
	STRID_SPLAT_NOISE_STRENGTH,
	STRID_SPLAT_NOISE_STRENGTH_X,
	STRID_SPLAT_NOISE_STRENGTH_Y,
	STRID_SPLAT_NOISE_STRENGTH_Z,
	STRID_SPLAT_NOISE_OCTAVES,
	STRID_SPLAT_NOISE_PERSISTENCE,
	STRID_SPLAT_NOISE_LACUNARITY,

	STRID_SPLAT_OPACITY_TOPIC,
	STRID_SPLAT_OPACITY_ENABLE,
	STRID_SPLAT_MIN_OPACITY,
	STRID_SPLAT_MAX_OPACITY,
	STRID_SPLAT_OPACITY_RAMP,
	STRID_SPLAT_OPACITY_SHAPE_SIZE,
	STRID_SPLAT_OPACITY_SHAPE_SCALE_X,
	STRID_SPLAT_OPACITY_SHAPE_SCALE_Y,
	STRID_SPLAT_OPACITY_SHAPE_SCALE_Z,
	STRID_SPLAT_OPACITY_SHAPE_CENTER,
	STRID_SPLAT_OPACITY_SHAPE_FEATHER,

	STRID_SPLAT_DISPLACEMENT_TOPIC,
	STRID_SPLAT_DISPLACEMENT_ENABLE,
	STRID_SPLAT_DISPLACEMENT_OFFSET,
	STRID_SPLAT_DISPLACEMENT_OFFSET_RAMP,
	STRID_SPLAT_DISPLACEMENT_SCALE,
	STRID_SPLAT_DISPLACEMENT_SCALE_RAMP,
	STRID_SPLAT_DISPLACEMENT_ROTATION_X,
	STRID_SPLAT_DISPLACEMENT_ROTATION_Y,
	STRID_SPLAT_DISPLACEMENT_ROTATION_Z,
	STRID_SPLAT_DISPLACEMENT_ROTATION_RAMP,
	STRID_SPLAT_DISPLACEMENT_SHAPE_SIZE,
	STRID_SPLAT_DISPLACEMENT_SHAPE_SCALE_X,
	STRID_SPLAT_DISPLACEMENT_SHAPE_SCALE_Y,
	STRID_SPLAT_DISPLACEMENT_SHAPE_SCALE_Z,
	STRID_SPLAT_DISPLACEMENT_SHAPE_CENTER,
	STRID_SPLAT_DISPLACEMENT_SHAPE_FEATHER,

	STRID_SPLAT_DENSE_TOPIC, 
	STRID_SPLAT_DENSE_ENABLE, 
	STRID_SPLAT_DENSE_DENSITY,
	STRID_SPLAT_DENSE_DENSITY_RAMP,
	STRID_SPLAT_DENSE_SHAPE_SIZE,	
	STRID_SPLAT_DENSE_SHAPE_SCALE_X, 
	STRID_SPLAT_DENSE_SHAPE_SCALE_Y, 
	STRID_SPLAT_DENSE_SHAPE_SCALE_Z, 
	STRID_SPLAT_DENSE_SHAPE_CENTER, 
	STRID_SPLAT_DENSE_SHAPE_FEATHER,

	STRID_INVERT_SPHERE_TOPIC,
	STRID_INVERT_SPHERE_ENABLE,
	STRID_INVERT_SPHERE_CENTER,
	STRID_INVERT_SPHERE_RADIUS,
	STRID_INVERT_SPHERE_INTENSITY,
	STRID_INVERT_SPHERE_DISTANCE,
	STRID_INVERT_SPHERE_COMPRESSION,

	STRID_ADVANCED_TOPIC,
	STRID_ADVANCED_CAMERA_FOCAL_LENGTH,
	STRID_ADVANCED_SPLAT_CROP_NEAR,
	STRID_ADVANCED_SPLAT_CROP_FAR,
	STRID_ADVANCED_SPLAT_CROP_MAX_SCALE,
	STRID_ADVANCED_SPLAT_CROP_MIN_SCALE,

	STRID_KIRI_ADVANCED_DOF_TOPIC,
	STRID_KIRI_ADVANCED_DOF_ENABLE,
	STRID_KIRI_ADVANCED_DOF_FOCUS_DISTANCE,
	STRID_KIRI_ADVANCED_DOF_APERTURE,
	STRID_KIRI_ADVANCED_DOF_BLUR_LEVEL,

	STRID_KIRI_ADVANCED_GLOW_TOPIC,
	STRID_KIRI_ADVANCED_GLOW_ENABLE,
	STRID_KIRI_ADVANCED_GLOW_BLEND_MODE,
	STRID_KIRI_ADVANCED_GLOW_RADIUS,
	STRID_KIRI_ADVANCED_GLOW_THRESHOLD,
	STRID_KIRI_ADVANCED_GLOW_SMOOTH,

	STRID_NUMTYPES

} StrIDType;

