#version 450 core

#include "define.glsl"
#include "struct.glsl"
#include "noise.glsl"
#include "bezierCurve.glsl"
#include "geometry.glsl"

layout(local_size_x = 256) in;

layout(std430, binding = 0) buffer PositionBuffer
{
    float position[];
};

layout( std140  , binding = 1) uniform BezierCurveBuffer {
    BezierCurveInfo u_colorRamp;
    BezierCurveInfo u_splatScaleRamp;
    BezierCurveInfo u_splatOpacityRamp;
    BezierCurveInfo u_splatDisplacementOffsetRamp;
    BezierCurveInfo u_splatDisplacementScaleRamp;
    BezierCurveInfo u_splatDisplacementRotationRamp;
};

layout( std140 , binding = 2) uniform RenderInfoBuffer {
    RenderInfo u_renderInfo;
};

layout(std430, binding = 3) buffer ViewPositionBuffer
{
    float viewPosition[];
};

void main()
{
    int idx = int(gl_GlobalInvocationID.x);


    if(idx >= u_renderInfo.splatCount){
        return;
    }

    int header = idx * 3 ;
    vec4 positionLocal = vec4(position[header + 0], position[header + 1], position[header + 2], 1.0f);
    vec3 positionAnchor = (u_renderInfo.anchorModelMatrix * positionLocal).xyz;
    vec3 anchorPoint = (u_renderInfo.anchorModelMatrix * vec4(0.0, 0.0, 0.0, 1.0)).xyz;
    // compute animate here

    vec3 displaceOffset = vec3(0.0);
    vec3 noiseOffset = vec3(0.0);
    
   if (u_renderInfo.splatNoiseEnable == 1.0)
    {
        float noiseRadiusBound = max(10 * u_renderInfo.splatNoiseShapeSize, 0.0001);
        vec3 noiseNormalDir = (positionAnchor - u_renderInfo.splatNoiseShapeCenter.xyz);
        noiseNormalDir /= u_renderInfo.splatNoiseShapeScaleXYZ.xyz * PERCENT;
        float noiseMask = step(length(noiseNormalDir), noiseRadiusBound);
    
        int octaves = u_renderInfo.splatNoiseOctaves;
        float persistence = u_renderInfo.splatNoisePersistence * PERCENT;
        float lacunarity = u_renderInfo.splatNoiseLacunarity * PERCENT;
        vec3 p = positionAnchor;
        vec3 noiseValue;
        vec3 offset1 = vec3(13.57, 47.13, 29.63) * 1000.0;
        vec3 offset2 = vec3(73.19, 57.21, 89.47) * 1000.0;
    
        noiseValue.x = u_renderInfo.splatNoiseStrengthX * PERCENT * FBM(p , octaves, persistence, lacunarity);
        noiseValue.y = u_renderInfo.splatNoiseStrengthY * PERCENT * FBM(p + offset1, octaves, persistence, lacunarity);
        noiseValue.z = u_renderInfo.splatNoiseStrengthZ * PERCENT * FBM(p + offset2, octaves, persistence, lacunarity);
        
        noiseOffset = noiseValue * 10 * u_renderInfo.splatNoiseStrength * noiseMask;
    }
    

    if (u_renderInfo.splatDisplacementEnable == 1.0)
    {
        float displaceRadiusBound = max(10 * u_renderInfo.splatDisplacementShapeSize, 0.0001);
        vec3 displaceNormalDir = (positionAnchor - u_renderInfo.splatDisplacementShapeCenter.xyz);
        displaceNormalDir /= u_renderInfo.splatDisplacementShapeScaleXYZ.xyz * PERCENT;
        float displaceNormalLength = length(displaceNormalDir);
        float displaceMask = step(displaceNormalLength, displaceRadiusBound);
    
        float displaceLerpFactor = displaceNormalLength / displaceRadiusBound;
    
        float displaceOffsetRampFactor = 1.0 - GetValueFromBezierCurve(u_splatDisplacementOffsetRamp , displaceLerpFactor);
        float displaceScaleRampFactor = 1.0 - GetValueFromBezierCurve(u_splatDisplacementScaleRamp, displaceLerpFactor);
        float displaceRotationRampFactor = 1.0 - GetValueFromBezierCurve(u_splatDisplacementRotationRamp, displaceLerpFactor);
    
        float displaceScaleValue = mix(1.0, u_renderInfo.splatDisplacementScale * PERCENT, displaceScaleRampFactor);
        vec3 displaceRotationValue = mix(vec3(0.0), radians(u_renderInfo.splatDisplacementRotation.xyz), displaceRotationRampFactor);
        vec3 displacePosition = displaceOffsetRampFactor * u_renderInfo.splatDisplacementOffset.xyz;
    
        mat4 displaceModelMatrix = translateMatrix(displacePosition) *
                               eulerRotationXYZ(displaceRotationValue) *
                               scaleMatrix(vec3(displaceScaleValue));

        vec4 targetDisplacePoint = displaceModelMatrix * vec4(positionAnchor, 1.0);
        displaceOffset = targetDisplacePoint.xyz - positionAnchor;
        //vec3 displaceOffset = u_renderInfo.splatDisplacementShapeCenter.xyz * u_renderInfo.splatDisplacementShapeSize * displaceMask;
        displaceOffset *= displaceMask;
    }
   
    positionAnchor += noiseOffset + displaceOffset;
    
     if (u_renderInfo.splatInvertSphereEnable == 1.0){
        //positionAnchor += sphereCenter;

        float R = max(u_renderInfo.splatInvertSphereRaduis, 1e-6);
        float intensity = clamp(u_renderInfo.splatInvertSphereIntensity, 0.0, 1.0);
        float D = u_renderInfo.splatInvertSphereDistance;
        float mu = max(u_renderInfo.splatInvertSphereCompression, 0.0) * PERCENT;
        
        vec3 sphereCenter = u_renderInfo.splatInvertSphereCenter.xyz;
        sphereCenter += anchorPoint;
        vec3 offset = positionAnchor - sphereCenter;
        
        float r = length(offset);
        
        vec3 direction = offset / r;
        float f_r = r ;
        
        if ( r > 1e-6) {
            float denom = 1.0 - (R / D);
        
            float v = ((R / r) - (R / D)) / denom;
            //v = clamp(v, 0.0, 1.0);
        
            float h = 0.0;
            if (abs(mu) < 1e-6) {
                h = v;
            } else {
                h = log(1.0 + mu * v) / log(1.0 + mu);
            }
        
            //f_r = mix( r , R * h , intensity) ;
            //positionAnchor = newPositionAnchor;
            float f_r_raw = mix(r, R * h, intensity);  
            f_r = f_r_raw;
            
            //if (f_r_raw > r) {
            //    float ratio = r / f_r_raw;              
            //    f_r = r * ratio;                        
            //} else {
            //    f_r = f_r_raw;                          
            //}
        }
         positionAnchor = sphereCenter + direction * f_r;
    }





    vec4 positionWorld = u_renderInfo.transformModelMatrix * vec4(positionAnchor, 1.0);

    vec4 positionView  = u_renderInfo.viewMatrix * positionWorld;

    viewPosition[header + 0] =  positionView.x;
    viewPosition[header + 1] =  positionView.y;
    viewPosition[header + 2] =  positionView.z;
}
